// Styles the administrator login and other authentication-state screens.

import { StyleSheet } from "react-native";

import { colors, radii } from "@/constants/admin-theme";

export const authScreenStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: colors.background,
    overflow: 'hidden',
  },
  loginBackdrop: {
    ...StyleSheet.absoluteFillObject,
    pointerEvents: 'none',
  },
  backdropGlow: {
    position: 'absolute',
    top: -90,
    right: -100,
    width: 310,
    height: 310,
    borderRadius: 155,
    backgroundColor: colors.sage,
    opacity: 0.68,
  },
  courtDrawing: {
    position: 'absolute',
    top: 76,
    right: -42,
    width: 230,
    height: 350,
    transform: [{ rotate: '12deg' }],
    opacity: 0.48,
  },
  courtOuterLine: {
    ...StyleSheet.absoluteFillObject,
    borderWidth: 2,
    borderColor: colors.accent,
    borderRadius: 28,
  },
  courtCenterLine: {
    position: 'absolute',
    top: '50%',
    left: 0,
    right: 0,
    borderTopWidth: 2,
    borderTopColor: colors.accent,
  },
  courtServiceLine: {
    position: 'absolute',
    top: '25%',
    bottom: '25%',
    left: '50%',
    borderLeftWidth: 2,
    borderLeftColor: colors.accent,
  },
  courtNet: {
    position: 'absolute',
    top: '50%',
    left: -8,
    right: -8,
    height: 9,
    marginTop: -4,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: colors.text,
    opacity: 0.7,
  },
  ballMark: {
    position: 'absolute',
    right: 58,
    bottom: 54,
    width: 74,
    height: 74,
    borderRadius: 37,
    backgroundColor: colors.ballGreen,
    opacity: 0.8,
  },
  folioRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    paddingVertical: 16,
  },
  folio: {
    color: colors.accent,
    fontSize: 52,
    lineHeight: 54,
    fontWeight: '900',
    letterSpacing: -2.5,
  },
  product: {
    color: colors.text,
    fontSize: 14,
    fontWeight: '700',
  },
  loginBody: {
    flex: 1,
    justifyContent: 'center',
    paddingVertical: 30,
  },
  loginCard: {
    width: '100%',
    maxWidth: 540,
    padding: 24,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radii.large,
    backgroundColor: colors.surface,
    shadowColor: colors.text,
    shadowOffset: { width: 0, height: 18 },
    shadowOpacity: 0.1,
    shadowRadius: 28,
    elevation: 5,
  },
  eyebrow: {
    color: colors.accent,
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 1.4,
    marginBottom: 12,
  },
  title: {
    color: colors.text,
    fontSize: 40,
    lineHeight: 42,
    fontWeight: '800',
    letterSpacing: -1.5,
    maxWidth: 520,
  },
  intro: {
    color: colors.muted,
    fontSize: 15,
    lineHeight: 22,
    marginTop: 14,
    maxWidth: 520,
  },
  form: {
    gap: 18,
    marginTop: 34,
    maxWidth: 520,
  },
  field: {
    gap: 7,
  },
  label: {
    color: colors.text,
    fontSize: 13,
    fontWeight: '700',
  },
  input: {
    minHeight: 52,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    color: colors.text,
    fontSize: 16,
    paddingHorizontal: 14,
    borderRadius: radii.small,
  },
  passwordRow: {
    minHeight: 52,
    flexDirection: 'row',
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    borderRadius: radii.small,
  },
  passwordInput: {
    flex: 1,
    color: colors.text,
    fontSize: 16,
    paddingHorizontal: 14,
  },
  passwordToggle: {
    width: 50,
    alignItems: 'center',
    justifyContent: 'center',
  },
  centered: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 14,
  },
  centeredContent: {
    flex: 1,
    alignItems: 'flex-start',
    justifyContent: 'center',
    gap: 14,
  },
  loadingText: {
    color: colors.muted,
    fontSize: 14,
  },
});
