// Styles the camera scanner, manual-code form, and receipt details.

import { StyleSheet } from "react-native";

import { colors, layout } from "@/constants/admin-theme";

export const receiptScannerStyles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#05070C' },
  header: {
    minHeight: 78,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 16,
    paddingHorizontal: layout.gutter,
    borderBottomWidth: 1,
    borderBottomColor: '#2A2D35',
  },
  eyebrow: { color: '#AEB8D8', fontSize: 10, fontWeight: '800', letterSpacing: 1.2, textTransform: 'uppercase' },
  headerTitle: { color: colors.white, fontSize: 22, fontWeight: '900', letterSpacing: -0.6, marginTop: 4 },
  headerButton: { width: 44, height: 44, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: '#454955' },
  lookupStage: { flex: 1 },
  cameraStage: { flex: 1 },
  camera: { flex: 1 },
  scanOverlay: { flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(2, 5, 12, 0.24)' },
  scanFrame: { width: 254, height: 254, position: 'relative' },
  corner: { width: 42, height: 42, position: 'absolute', borderColor: colors.accent },
  cornerTopLeft: { top: 0, left: 0, borderTopWidth: 5, borderLeftWidth: 5 },
  cornerTopRight: { top: 0, right: 0, borderTopWidth: 5, borderRightWidth: 5 },
  cornerBottomLeft: { bottom: 0, left: 0, borderBottomWidth: 5, borderLeftWidth: 5 },
  cornerBottomRight: { right: 0, bottom: 0, borderRightWidth: 5, borderBottomWidth: 5 },
  scanLine: { position: 'absolute', top: '50%', left: 18, right: 18, height: 2, backgroundColor: colors.accent },
  cameraFooter: { minHeight: 118, padding: layout.gutter, gap: 15, backgroundColor: '#05070C' },
  cameraCopy: { paddingRight: 62 },
  cameraTitle: { color: colors.white, fontSize: 17, fontWeight: '800' },
  cameraInstruction: { color: '#AEB1BA', fontSize: 13, lineHeight: 19, marginTop: 5 },
  torchButton: { position: 'absolute', top: 20, right: 20, width: 46, height: 46, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: '#454955' },
  torchButtonActive: { backgroundColor: colors.surface, borderColor: colors.white },
  errorCard: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12, paddingTop: 13, borderTopWidth: 1, borderTopColor: '#454955' },
  errorText: { flex: 1, color: '#FFCFD7', fontSize: 13, lineHeight: 18 },
  tryAgain: { color: colors.white, fontSize: 13, fontWeight: '800', textDecorationLine: 'underline' },
  manualLookup: { gap: 13, padding: layout.gutter, borderTopWidth: 1, borderTopColor: '#2A2D35', backgroundColor: '#10141B' },
  manualHeading: { flexDirection: 'row', alignItems: 'center', gap: 11 },
  manualIcon: { width: 38, height: 38, alignItems: 'center', justifyContent: 'center', borderRadius: 19, backgroundColor: '#D9E8F2' },
  manualTitle: { color: colors.white, fontSize: 15, fontWeight: '800' },
  manualCopy: { color: '#AEB1BA', fontSize: 12, lineHeight: 17, marginTop: 2 },
  manualForm: { flexDirection: 'row', gap: 10 },
  manualInput: { flex: 1, minHeight: 50, paddingHorizontal: 15, borderWidth: 1, borderColor: '#5A606C', borderRadius: 16, backgroundColor: '#05070C', color: colors.white, fontSize: 17, fontWeight: '700', letterSpacing: 1.3 },
  manualButton: { width: 52, height: 50, alignItems: 'center', justifyContent: 'center', borderRadius: 16, backgroundColor: colors.accent },
  manualButtonPressed: { opacity: 0.72 },
  manualButtonDisabled: { opacity: 0.42 },
  centerState: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 14 },
  stateText: { color: colors.white, fontSize: 14, fontWeight: '700' },
  permissionCard: { margin: layout.gutter, marginTop: 56, gap: 16, padding: 20, backgroundColor: colors.surface, borderLeftWidth: 6, borderLeftColor: colors.accent },
  permissionIcon: { width: 52, height: 52, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.paleAccent },
  permissionTitle: { color: colors.text, fontSize: 23, fontWeight: '900', letterSpacing: -0.7 },
  permissionCopy: { color: colors.muted, fontSize: 14, lineHeight: 21 },
  receiptScroll: { flexGrow: 1, gap: 18, padding: layout.gutter, paddingBottom: 48, backgroundColor: colors.background },
  verifiedRow: { flexDirection: 'row', alignItems: 'center', gap: 13, paddingBottom: 17, borderBottomWidth: 1, borderBottomColor: colors.text },
  verifiedIcon: { width: 42, height: 42, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.accent },
  verifiedTitle: { color: colors.text, fontSize: 18, fontWeight: '900' },
  verifiedCopy: { color: colors.muted, fontSize: 12, lineHeight: 17, marginTop: 2 },
  passCodeBlock: { padding: 18, backgroundColor: colors.accent },
  passCodeLabel: { color: '#D8E1FF', fontSize: 10, fontWeight: '800', letterSpacing: 1.1, textTransform: 'uppercase' },
  passCode: { color: colors.white, fontSize: 34, fontWeight: '900', letterSpacing: 3, marginTop: 7 },
  chipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  detailGroup: { borderTopWidth: 1, borderTopColor: colors.text },
  detailGroupTitle: { color: colors.accent, fontSize: 11, fontWeight: '800', letterSpacing: 1, paddingVertical: 11, textTransform: 'uppercase' },
  detailRow: { flexDirection: 'row', justifyContent: 'space-between', gap: 18, borderTopWidth: 1, borderTopColor: colors.border, paddingVertical: 12 },
  detailLabel: { color: colors.muted, fontSize: 13 },
  detailValue: { flex: 1, color: colors.text, fontSize: 13, fontWeight: '700', textAlign: 'right' },
  flexField: { flex: 1 },
});
