// Styles reservation archive filters, results, and pagination controls.

import { StyleSheet } from "react-native";

import { colors } from "@/constants/admin-theme";

export const reservationArchiveStyles = StyleSheet.create({
  scrollContent: { paddingVertical: 22, paddingBottom: 48, gap: 20 },
  archiveIntro: { gap: 5 },
  archiveTitle: { color: colors.text, fontSize: 26, lineHeight: 30, fontWeight: '900', letterSpacing: -1 },
  archiveCopy: { color: colors.muted, fontSize: 13, lineHeight: 19 },
  filters: { gap: 16, padding: 15, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border },
  filterGroup: { gap: 7 },
  filterLabel: { color: colors.text, fontSize: 13, fontWeight: '700' },
  filterOptions: { flexDirection: 'row', flexWrap: 'wrap', gap: 7 },
  filterOption: { minHeight: 36, justifyContent: 'center', paddingHorizontal: 11, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface },
  filterOptionSelected: { backgroundColor: colors.accent, borderColor: colors.accent },
  filterOptionText: { color: colors.text, fontSize: 12, fontWeight: '700' },
  filterOptionTextSelected: { color: colors.onAccent },
  dateFields: { flexDirection: 'row', gap: 10 },
  flexField: { flex: 1 },
  filterActions: { flexDirection: 'row', alignItems: 'stretch', gap: 10 },
  clearButton: { minWidth: 72, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface },
  clearButtonText: { color: colors.accent, fontSize: 14, fontWeight: '800' },
  resultHeading: { flexDirection: 'row', alignItems: 'baseline', justifyContent: 'space-between', gap: 12, paddingBottom: 11, borderBottomWidth: 1, borderBottomColor: colors.text },
  resultCount: { color: colors.text, fontSize: 18, fontWeight: '900', letterSpacing: -0.4 },
  resultRange: { color: colors.muted, fontSize: 11, fontWeight: '700' },
  loadingState: { minHeight: 150, alignItems: 'center', justifyContent: 'center', gap: 10 },
  loadingText: { color: colors.muted, fontSize: 13 },
  resultList: { borderTopWidth: 1, borderTopColor: colors.border },
  resultCard: { flexDirection: 'row', minHeight: 174, borderBottomWidth: 1, borderBottomColor: colors.border, backgroundColor: colors.surface },
  resultCardPressed: { backgroundColor: colors.background },
  resultDate: { width: 76, alignItems: 'flex-start', paddingTop: 14, paddingHorizontal: 10, borderRightWidth: 1, borderRightColor: colors.border },
  resultDay: { color: colors.accent, fontSize: 43, lineHeight: 44, fontWeight: '900', letterSpacing: -2.5 },
  resultMonth: { color: colors.text, fontSize: 11, fontWeight: '900', letterSpacing: 0.8, textTransform: 'uppercase' },
  resultYear: { color: colors.muted, fontSize: 10, fontWeight: '700', marginTop: 2 },
  resultDetails: { flex: 1, gap: 5, padding: 14 },
  resultTopLine: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8 },
  resultPlayer: { flex: 1, color: colors.text, fontSize: 16, fontWeight: '900' },
  resultUsername: { color: colors.accent, fontSize: 11, fontWeight: '700' },
  resultTime: { color: colors.text, fontSize: 13, fontWeight: '700', marginTop: 2 },
  resultChips: { flexDirection: 'row', flexWrap: 'wrap', gap: 7, marginTop: 3 },
  resultFooter: { flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-between', gap: 10, marginTop: 4 },
  resultMeta: { flex: 1, color: colors.muted, fontSize: 11, lineHeight: 16 },
  resultPrice: { color: colors.text, fontSize: 15, fontWeight: '900' },
});
